# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Girls-Coding-Day-Jekyll-blog-sogsong"

# 网站的主标题
title: "A story between me and technology"
# 网站副标题
subTitle: "我与材料科学与工程理论计算的故事(*^▽^*)"

# 其它配置, 可忽略, 无需修改
permalink: /:title/
